let BANK=[],bankLoaded=false,selectedLevel="",playerName="",questions=[],questionIndex=0,score=0,correct=0,attempts=0,locked=false,gameFinished=false,gameEndTime=0,questionEndTime=0,gameTimerId=null,questionTimerId=null;
const scoreEl=document.getElementById("score"),gameTimerEl=document.getElementById("gameTimer"),gameTimerBarEl=document.getElementById("gameTimerBar"),questionNumberEl=document.getElementById("questionNumber"),questionPointsEl=document.getElementById("questionPoints"),questionScoreBarEl=document.getElementById("questionScoreBar"),questionTextEl=document.getElementById("questionText"),answersEl=document.getElementById("answers"),feedbackEl=document.getElementById("feedback"),playerNameEl=document.getElementById("playerName");
function loadQuestions(){fetch("questions.json").then(r=>{if(!r.ok)throw Error("questions.json HTTP "+r.status);return r.json()}).then(data=>{if(!Array.isArray(data))throw Error("questions.json bukan array");BANK=data;bankLoaded=true;console.log("Question bank loaded:",BANK.length)}).catch(e=>{console.error("Question bank gagal dimuatkan:",e);bankLoaded=false})}
function showScreen(n){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));const t=document.getElementById(n+"Screen");if(t)t.classList.add("active");window.scrollTo({top:0,behavior:"instant"})}
function chooseLevel(level){selectedLevel=level;document.getElementById("selectedLevelLabel").textContent=level.toUpperCase();playerNameEl.value="";showScreen("name");setTimeout(()=>playerNameEl.focus(),100)}
function shuffle(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function beginGame(){if(!bankLoaded){alert("Question bank belum siap. Sila refresh page dan cuba lagi.");return}playerName=playerNameEl.value.trim();if(!playerName){alert("Masukkan nama dulu.");playerNameEl.focus();return}const pool=BANK.filter(q=>String(q.category).toLowerCase()===selectedLevel);if(!pool.length){alert("Tiada soalan untuk level ini.");return}questions=shuffle(pool);questionIndex=0;score=0;correct=0;attempts=0;locked=false;gameFinished=false;document.getElementById("levelBadge").textContent=selectedLevel.toUpperCase();scoreEl.textContent="0";showScreen("game");startGameTimer();showQuestion()}
function startGameTimer(){clearInterval(gameTimerId);gameEndTime=Date.now()+60000;gameTimerId=setInterval(()=>{if(gameFinished){clearInterval(gameTimerId);return}const r=Math.max(0,gameEndTime-Date.now());gameTimerEl.textContent=Math.ceil(r/1000);gameTimerBarEl.style.width=(r/600)+"%";if(r<=0){clearInterval(gameTimerId);finishGame()}},50)}
function showQuestion(){if(gameFinished)return;if(questionIndex>=questions.length){questions=shuffle(questions);questionIndex=0}const q=questions[questionIndex];locked=false;questionNumberEl.textContent="Soalan "+(questionIndex+1);questionTextEl.textContent=q.question;feedbackEl.textContent="";answersEl.innerHTML="";q.options.forEach((o,i)=>{const b=document.createElement("button");b.type="button";b.className="answer-button";b.textContent=o;b.onclick=()=>answerQuestion(i);answersEl.appendChild(b)});startQuestionTimer()}
function startQuestionTimer(){clearInterval(questionTimerId);questionEndTime=Date.now()+10000;updateQuestionScore();questionTimerId=setInterval(()=>{if(gameFinished){clearInterval(questionTimerId);return}const r=Math.max(0,questionEndTime-Date.now());updateQuestionScore();if(r<=0){clearInterval(questionTimerId);timeOutQuestion()}},50)}
function getCurrentQuestionScore(){const r=Math.max(0,questionEndTime-Date.now());return Math.max(0,Math.min(100,Math.ceil(r/100)))}
function updateQuestionScore(){const p=getCurrentQuestionScore();questionPointsEl.textContent=p;questionScoreBarEl.style.width=p+"%"}
function answerQuestion(selectedAnswer){if(locked||gameFinished)return;locked=true;clearInterval(questionTimerId);attempts++;const q=questions[questionIndex],buttons=document.querySelectorAll(".answer-button"),ca=Number(q.answer);buttons.forEach((b,i)=>{b.classList.add("disabled");if(i===ca)b.classList.add("correct")});if(selectedAnswer===ca){const p=getCurrentQuestionScore();score+=p;correct++;scoreEl.textContent=score;feedbackEl.textContent="✅ Betul! +"+p+" points"}else{buttons[selectedAnswer].classList.add("wrong");feedbackEl.textContent="❌ Salah!"}setTimeout(()=>{if(!gameFinished){questionIndex++;showQuestion()}},450)}
function timeOutQuestion(){if(locked||gameFinished)return;locked=true;attempts++;const q=questions[questionIndex],buttons=document.querySelectorAll(".answer-button");buttons.forEach((b,i)=>{b.classList.add("disabled");if(i===Number(q.answer))b.classList.add("correct")});questionPointsEl.textContent="0";questionScoreBarEl.style.width="0%";feedbackEl.textContent="⏰ Masa habis!";setTimeout(()=>{if(!gameFinished){questionIndex++;showQuestion()}},450)}
function finishGame(){if(gameFinished)return;gameFinished=true;clearInterval(gameTimerId);clearInterval(questionTimerId);gameTimerEl.textContent="0";gameTimerBarEl.style.width="0%";saveScore();document.getElementById("resultScore").textContent=score;document.getElementById("resultCorrect").textContent=correct;document.getElementById("resultAttempts").textContent=attempts;let m="Good game! 🔥";if(score>=1500)m="Legend! 🔥🔥🔥";else if(score>=1000)m="Power! 🔥🔥";else if(score>=500)m="Nice! 🔥";document.getElementById("resultTitle").textContent=m;showScreen("result")}
function saveScore(){let l=JSON.parse(localStorage.getItem("bwr_leaderboard")||"[]");l.push({name:playerName,level:selectedLevel,score});l.sort((a,b)=>b.score-a.score);localStorage.setItem("bwr_leaderboard",JSON.stringify(l.slice(0,100)))}
function showLeaderboard(){clearInterval(gameTimerId);clearInterval(questionTimerId);const list=document.getElementById("leaderboardList"),l=JSON.parse(localStorage.getItem("bwr_leaderboard")||"[]");if(!l.length){list.innerHTML='<div class="empty">Belum ada score lagi.</div>';showScreen("leaderboard");return}list.innerHTML="";l.forEach((item,i)=>{const row=document.createElement("div");row.className="leaderboard-row";const rank=document.createElement("div");rank.className="rank";rank.textContent=i===0?"🥇":i===1?"🥈":i===2?"🥉":"#"+(i+1);const player=document.createElement("div"),name=document.createElement("div"),level=document.createElement("div"),ps=document.createElement("div");name.className="player-name";name.textContent=item.name;level.className="player-level";level.textContent=item.level;player.append(name,level);ps.className="player-score";ps.textContent=item.score;row.append(rank,player,ps);list.appendChild(row)});showScreen("leaderboard")}
function clearLeaderboard(){if(!confirm("Clear semua leaderboard pada device ini?"))return;localStorage.removeItem("bwr_leaderboard");showLeaderboard()}
function goHome(){clearInterval(gameTimerId);clearInterval(questionTimerId);gameFinished=true;showScreen("home")}
playerNameEl.addEventListener("keydown",e=>{if(e.key==="Enter")beginGame()});
loadQuestions();
